FROM balenalib/%%BALENA_MACHINE_NAME%%-node


WORKDIR /usr/src/app

COPY index.js .
COPY package.json .
COPY start.sh .
RUN chmod u+x start.sh
RUN install_packages git
RUN npm install

CMD ["bash","start.sh"]